### PR TITLE
link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello!

The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that suggestion.

Cheers :-)

### CODE REVIEW

**Comment by acatejr** [comment]
What is a "PR"?

**Comment by katrinleinweber** [comment]
Did I change a part of the code that _detects_ existing DOI links? That would be a mistake on my part. Apologies in that case! Otherwise, could you please let me know why you closed this? Thanks :-)

**Comment by laszewsk** [comment]
my mistake. I looked wrong, I thought these were done to the hid-sample.

**Comment by laszewsk** [comment]
please undo change.

**Comment by katrinleinweber** [comment]
It seems https://github.com/cloudmesh-community/hid-sp18-505/commit/5832296a71e4250595b4aa3a68262afb20628f1b solved this PR in another way ;-)

I'd say the update to https://github.com/cloudmesh-community/hid-sample/ is sufficient in the long-term. Thanks for merging that one :-) It's actually my mistake in part, because I should have realised this and other repos are individual's projects. IMHO, this can be closed.

**Comment by acatejr** [comment]
@laszewsk How do I deal with this in terms of my work?  Thx.

**Comment by katrinleinweber** [comment]
IMHO, not immediately. Just, when you see code that generates a DOI links using `http://dx.doi.org/`, consider updating it to `https://doi.org/` ;-)   My apologies for any confusion this PR might have caused! I should have realised that it would be more useful to send it to `hid-sample` only.

**Pull request closed without merging**
